### ISSUE TITLE
the SQLiteDb.cs file results in unbuild able code due to unclear references

### ISSUE THREAD

**Issue by NCleverly** [azdevelopnet/CommonCore#1]
Line 27 					conn = new SQLiteAsyncConnection(System.IO.Path.Combine(folder, CoreSettings.Config.SqliteSettings.SQLiteDatabase));

cause a failure due to not providing the ISQLitePlatform implentation and the code has no current to determine this. 

May i missing something or can you provide what nuget packages are required for the common core to work including the versions?

**Comment by NCleverly** [comment]
@azdevelopnet Please read the above as it is an issue preventing me from completing the SQLite demo

**Comment by azdevelopnet** [comment]
Look into this and get back-to you shortly 


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Nate Cleverly <notifications@github.com> Date: 8/5/17  4:44 PM  (GMT-07:00) To: azdevelopnet/CommonCore <CommonCore@noreply.github.com> Cc: azdevelopnet <azdevelop.net@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [azdevelopnet/CommonCore] the SQLiteDb.cs file results in unbuild
  able code due to unclear references (#1) 
@azdevelopnet Please read the above as it is an issue preventing me from completing the SQLite demo

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/azdevelopnet/CommonCore","title":"azdevelopnet/CommonCore","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/azdevelopnet/CommonCore"}},"updates":{"snippets":[{"icon":"PERSON","message":"@NCleverly in #1: @azdevelopnet Please read the above as it is an issue preventing me from completing the SQLite demo"}],"action":{"name":"View Issue","url":"https://github.com/azdevelopnet/CommonCore/issues/1#issuecomment-320476612"}}}
